name: CI

on:
  push:
    tags: *
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get the version number
        run: echo "VERNUM=$(awk -F'\"' '/version_number/ { print $4 }' manifest.json)" >> $GITHUB_ENV

      - name: Compress the files into a zip archive
        uses: thedoctor0/zip-release@master
        with:
          filename: "RoR2akamikebModpack-${{env.VERNUM}}.zip"
          exclusions: "*.git*"

      - name: Upload artifacts as release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "RoR2akamikebModpack-${{env.VERNUM}}.zip"
          token: ${{secrets.GITHUB_TOKEN}}
          tag: v${{env.VERNUM}}
